# Site settings
title: Precious Plastic
url: http://preciousplastic.com
baseurl: ''
description: Turn plastic waste into new valuable things

sass:
  style: compressed

exclude: ['CNAME', '*.md']
permalink: pretty

gems:
  - jekyll-sitemap
