# Site settings
title: Precious Plastic
url: http://preciousplastic.com
baseurl: ''
description: Turn plastic waste into new valuable things

sass:
  style: compressed

exclude: ['CNAME', '*.md']
permalink: pretty

gems:
  - jekyll-sitemap

# This is used for the language selector, should contain native name of the 
# language and the language abbreviation used in the 'lang' variable of the 
# pages.
languages:
  - name: 'English'
    key: 'en'
