# Site settings
title: Precious Plastic
url: http://preciousplastic.com
baseurl: ''
description: Turn plastic waste into new valuable things

sass:
  style: compressed

exclude: ['CNAME', '*.md']
permalink: pretty

gems:
  - jekyll-sitemap

# This is used for the language selector, should contain native name of the
# language and the language abbreviation used in the 'lang' variable of the
# pages.
languages:
  - name: 'English'
    key: 'en'
  - name: 'Deutsch'
    key: 'de'

# Set the lang variable for all files in the language directory
defaults:
  -
    scope:
      path: 'en'
    values:
      lang: 'en'
      translations:
        videos:
          title: 'Start'
          menu-title: 'Videos'
          mobile-title: 'Chapters'
        about:
          title: 'About'
        faq:
          title: 'FAQ'
        help-us:
          title: 'Help Us'
        thanks:
          title: 'Thanks'
        terms:
          title: 'Terms'
        contact:
          title: 'Contact'
        donate:
          title: 'Donate'
        by:
          title: 'A project by Dave Hakkens'
        overlay:
          spread: 'Spread the knowledge!'
          reach: 'Make sure it reaches your friend, uncle, and that farmer living in Africa.'
          shares: 'Total shares:'
          want: 'We need'
          SPREAD: 'HELP'
          magic: 'to plastic recycling all over the world!'
  -
    scope:
      path: 'de'
    values:
      lang: 'de'
      translations:
        videos:
          title: 'Start'
          menu-title: 'Videos'
          mobile-title: 'Maschinen'
        about:
          title: 'Über'
        faq:
          title: 'FAQ'
        help-us:
          title: 'Helfen'
        thanks:
          title: 'Team'
        terms:
          title: 'Bedingungen'
        contact:
          title: 'Kontakt'
        donate:
          title: 'Spenden'
        by:
          title: 'Ein Projekt von Dave Hakkens'
        overlay:
          spread: 'Teile das Wissen!'
          reach: 'Und gehe sicher, dass es deinen Freund, Onkel, und den Bauern in Afrika erreicht.'
          shares: 'Posts über uns:'
          want: 'Möchtest du helfen?'
          SPREAD: 'TEILE'
          magic: 'das Projekt und lass der Magie ihren Lauf.'
